File Input/Output :

Let's create a file named example.txt and write some text to it. Then, we'll read the text and finally close the file.


**Writing to a File**

In [ ]:
# Open file in write mode, this will create the file if it doesn't exist
with open("example.txt", "w") as file:
    # Write some text to the file
    file.write("Hello, this is line 1.\n")
    file.write("And this is line 2.\n")
# File is automatically closed when exiting the 'with' block


Without newline

In [ ]:
# Open file in write mode, this will create the file if it doesn't exist
with open("example2.txt", "w") as file:
    # Write some text to the file
    file.write("Hello, this is line 1.")
    file.write("And this is line 2.")
# File is automatically closed when exiting the 'with' block


**Reading from a File**

In [ ]:
# Open file in read mode
with open("example.txt", "r") as file:
    # Read the entire file content into a string
    file_content = file.read()
    print("Entire file content:")
    print(file_content)


Entire file content:
Hello, this is line 1.
And this is line 2.



In [ ]:
# Open file in read mode
with open("example2.txt", "r") as file:
    # Read the entire file content into a string
    file_content = file.read()
    print("Entire file content:")
    print(file_content)


Entire file content:
Hello, this is line 1.And this is line 2.


**Reading Line-by-Line**

In [ ]:
# Open file in read mode
with open("example.txt", "r") as file:
    # Read file line-by-line
    print("Reading line-by-line:")
    for line in file:
        print(line, end='')  # the 'end=""' removes extra newline character


Reading line-by-line:
Hello, this is line 1.
And this is line 2.


**Collections Library**

**namedtuple** is used to create tuple-like classes that have fields accessible by attribute lookup. They're similar to tuples but more readable.

In [ ]:
from collections import namedtuple

# Define a named tuple class called 'Point'
Point = namedtuple('Point', 'x y z')

# Create an instance of Point
p = Point(1, 2)

# Access the fields
print(p.x)  # Output: 1
print(p.y)  # Output: 2


Dict to Tuple

In [ ]:
import sys

In [ ]:
Person = namedtuple('Person', ['name', 'age'])
person_dict = {'name': 'Alice', 'age': 30}
person_tuple = Person(**person_dict)
print("Memory size of namedtuple:", sys.getsizeof(person_tuple))
print("Memory size of dict:", sys.getsizeof(person_dict))


Memory size of namedtuple: 56
Memory size of dict: 232


In [ ]:
person_tuple._replace(age=50)

Person(name='Alice', age=50)

A **deque** (double-ended queue) is like a list but optimized for appending and popping from both ends.

In [ ]:
from collections import deque

# Create a deque
dq = deque([1, 2, 3])

# Append to the left
dq.appendleft(0)
print(dq)  # Output: deque([0, 1, 2, 3])

# Pop from the right
dq.pop()
print(dq)  # Output: deque([0, 1, 2])


deque([0, 1, 2, 3])
deque([0, 1, 2])


**Counter** is a dictionary subclass for counting hashable objects. It's a collection where elements are stored as keys and their counts are stored as values.

In [ ]:
from collections import Counter

# Count the occurrences of each character in a string
c = Counter("abracadabra")
print(c)  # Output: Counter({'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1})


Counter({'a': 5, 'b': 2, 'r': 2, 'c': 1, 'd': 1})


In [ ]:
sentence = "This is a sample sentence, and this sentence has some sample words like sentence and words."
words = sentence.lower().replace(',', '').replace('.', '').split()
print(words)
word_count = Counter(words)
print(word_count)

['this', 'is', 'a', 'sample', 'sentence', 'and', 'this', 'sentence', 'has', 'some', 'sample', 'words', 'like', 'sentence', 'and', 'words']
Counter({'sentence': 3, 'this': 2, 'sample': 2, 'and': 2, 'words': 2, 'is': 1, 'a': 1, 'has': 1, 'some': 1, 'like': 1})


In [ ]:
print("Most common words:", word_count.most_common(3))


Most common words: [('sentence', 3), ('this', 2), ('sample', 2)]


In [ ]:
sorted_words = sorted(word_count.items(), key=lambda x: x[1], reverse=True)
print("Sorted words by count:", sorted_words)


Sorted words by count: [('sentence', 3), ('this', 2), ('sample', 2), ('and', 2), ('words', 2), ('is', 1), ('a', 1), ('has', 1), ('some', 1), ('like', 1)]


**OrderedDict** is a dictionary subclass that remembers the order that items were added.

In [ ]:
from collections import OrderedDict

# Create an OrderedDict
od = OrderedDict(a=1, b=2, c=3)
print(od)  # Output: OrderedDict([('a', 1), ('b', 2), ('c', 3)])


OrderedDict([('a', 1), ('b', 2), ('c', 3)])


In [ ]:
regular_dict = {}
regular_dict['a'] = 1
regular_dict['b'] = 2
regular_dict['c'] = 3
print(regular_dict)


{'a': 1, 'b': 2, 'c': 3}


In [ ]:
ordered_dict = OrderedDict()
ordered_dict['a'] = 1
ordered_dict['b'] = 2
ordered_dict['c'] = 3
print(ordered_dict)  # Output: OrderedDict([('a', 1), ('b', 2), ('c', 3)])

# Reordering
ordered_dict.move_to_end('b', last=False)
print(ordered_dict)  # Output: OrderedDict([('b', 2), ('a', 1), ('c', 3)])

OrderedDict([('a', 1), ('b', 2), ('c', 3)])
OrderedDict([('b', 2), ('a', 1), ('c', 3)])


**defaultdict** is another dictionary subclass that will return a default value if a key doesn't exist.



In [ ]:
from collections import defaultdict

# Create a defaultdict
dd = defaultdict(float)
dd['a']=1.0
dd['b'] =2.0

print(dd['a'])
# Access a missing key
print(dd['missing_key'])  # Output: 0


1.0
0.0


**map**

A built-in function that applies a given function to all items of an iterator and returns an iterator that produces the results.

The map function returns an iterator, which means you can only iterate through it once, and it doesn't support indexing or slicing like lists do. However, you can convert it to a list to see its elements.

In [ ]:
words = ["apple", "banana", "carrot", "avocado", "cucumber", "cheese"]

# Get the first letter of each word using map
first_letters = map(lambda x: x[0], words)
# print(list(first_letters))
# Use Counter to count the occurrences of each first letter
letter_count = Counter(list(first_letters))


# Convert it to a dictionary
letter_count_dict = dict(letter_count)

print(letter_count_dict)

{'a': 2, 'b': 1, 'c': 3}


**Numpy**

In [ ]:
import numpy as np

Creating arrays

In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr1

array([1, 2, 3])

In [ ]:
arr2 = np.zeros((2, 3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr3 = np.ones((3, 2))
arr3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
arr4 = np.empty((2, 2))
arr4

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [ ]:
arr5 = np.arange(0, 10, 2)  # Start, stop, step
arr5

array([0, 2, 4, 6, 8])

In [ ]:
arr8 = np.full((2, 2), 7)
arr8

array([[7, 7],
       [7, 7]])

Efficiency of NumPy

In [ ]:
import time

# Create a large list and a NumPy array
start_time = time.time()
large_list = list(range(1, 1000000))
end_time = time.time()
list_time = end_time - start_time
print(list_time)
start_time = time.time()
large_array = np.array(large_list)
end_time = time.time()
list_time = end_time - start_time
print(list_time)
# Measure time taken to sum elements in the list
start_time = time.time()
list_sum = sum([x * 2 for x in large_list])
end_time = time.time()
list_time = end_time - start_time
print(f"Time taken using Python lists: {list_time} seconds")

# Measure time taken to sum elements in the NumPy array
start_time = time.time()
array_sum = np.sum(large_array * 2)
end_time = time.time()
array_time = end_time - start_time
print(f"Time taken using NumPy arrays: {array_time} seconds")

# Calculate efficiency
efficiency_ratio = list_time / array_time
print(f"NumPy is approximately {efficiency_ratio:.2f} times faster for this operation.")


0.02035379409790039
0.056894779205322266
Time taken using Python lists: 0.06738638877868652 seconds
Time taken using NumPy arrays: 0.0018303394317626953 seconds
NumPy is approximately 36.82 times faster for this operation.


# **Review**

```
What does the 'w' mode in open() do?

A) Read a file
B) Write to a file
C) Append to a file
D) Read and Write to a file
```





```
What happens to the existing content in a file when you open it in 'w' mode?

A) Preserved
B) Deleted
C) Moved to another file
D) None of the above
```





```
What does the with statement do in file handling?

A) Creates a file
B) Closes the file automatically
C) Reads content from the file
D) Deletes the file
```





```
The write() method can write only one line at a time. True /False
```





```
What does the map function return?
 A) A list
 B) A tuple
 C) A dictionary
 D) A map object

```





```
What is the default value for the defaultdict if not specified?
 0
 None
 An empty list
 An empty dictionary

```







```
What will happen if you try to add a mutable object like a list to a set?
 It will be added successfully
 An error will be thrown
 It will be converted to a tuple
 The set will become immutable
```



In [ ]:
# Create a set
my_set = {1, 2, 3}

# Try to add a list to the set
try:
    my_set.add({'a':1})
except TypeError as e:
    print(f"An error occurred: {e}")
print(my_set)


An error occurred: unhashable type: 'dict'
{1, 2, 3}


In [ ]:
#What will be the output?
array = np.random.rand(2, 2)
array

array([[0.66393228, 0.48295759],
       [0.74804246, 0.65575501]])

In [ ]:
#What will be the output?
array = np.eye(3)
array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Try what kind of array (np.linspace(0, 1, 5)) creates

In [ ]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])